apiVersion: v1
kind: Template
metadata:
  name: artifactory
  annotations:
    description: "A template to instantiate Jfrog Artifactory"
    tags: "artifactory,jfrog"
labels:
  artifactory: ${NAME}
parameters:
- description: ""
  name: NAME
  required: true
- description: "Random 4 char string to append to NAME"
  name: RANDOM
  generate: expression
  from: "[a-zA-Z0-9]{5}"
- description: "The image tag for Artifactory"
  name: "IMAGE"
  required: true
- description: "The API endpoint for the image download plugin to hit with the image data"
  name: "JFROG_EVENT_PROCESSOR"
  required: true
  value: "http://operator-pipeline-api:8080/downloadEvent"
- description: "HTTP_PROXY"
  name: HTTP_PROXY
  required: false
- description: "HTTPS_PROXY"
  name: HTTPS_PROXY
  required: false
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      artifactory: ${NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        artifactory: ${NAME}
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          artifactory: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - env:
          - name: http_proxy
            value: ${HTTP_PROXY}
          - name: https_proxy
            value: ${HTTPS_PROXY}
          - name: JFROG_EVENT_PROCESSOR
            value: ${JFROG_EVENT_PROCESSOR}          
          image: ${IMAGE}
          imagePullPolicy: Always
          name: ${NAME}
          ports:
          - containerPort: 8081
            name: http
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 4Gi
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    port:
      targetPort: http
    to:
      kind: Service
      name: ${NAME}
      weight: 100
    wildcardPolicy: None
